version: '3.1'

services:

  db:
    container_name: postgres_contacts
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contacts    
    volumes:
      - ./db:/docker-entrypoint-initdb.db
      - /var/lib/postgres_data:/var/lib/postgres/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080
    
  backend:
    depends_on:
      - db
    build:
      context: ./java
      args: 
        JAR_FILE: "*.jar"
    ports:
      - 8080:8080
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contacts
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root

  frontend:
    depends_on:
      - backend
    build:
      context: ./angular
    container_name: contact-app-front
    ports:
      - 80:80