version: '3.1'

services:

  db:
    container_name: postgres_contacts
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contacts    

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080
    
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        JAR_FILE: devops-0.0.1-SNAPSHOT.jar
    ports:
      - 80:80
      - 8080:8080
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contacts
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
